#!/bin/sh

/usr/bin/python /usr/bin/noip.py /etc/noip.conf

EXITVALUE=$?
if [ $EXITVALUE != 0 ]
then
    /usr/bin/logger -t noip-sync "ALERT exited abnormally with [$EXITVALUE]"
else
    /usr/bin/logger -t noip-sync "INFO successfully updated IP"
fi
exit 0
